
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoMVCEF.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DEPT
{

    public int DEPT_NO { get; set; }

    public string DNOMBRE { get; set; }

    public string LOC { get; set; }

}

}
