
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoMVCEF.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DOCTOR
{

    public string HOSPITAL_COD { get; set; }

    public int DOCTOR_NO { get; set; }

    public string APELLIDO { get; set; }

    public string ESPECIALIDAD { get; set; }

    public Nullable<int> SALARIO { get; set; }

}

}
