
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoMVCEF.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ENFERMO
{

    public string INSCRIPCION { get; set; }

    public string APELLIDO { get; set; }

    public string DIRECCION { get; set; }

    public Nullable<System.DateTime> FECHA_NAC { get; set; }

    public string S { get; set; }

    public string NSS { get; set; }

}

}
