
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoMVCEF.Models
{

using System;
    
public partial class PAGINACIONDOCTORESAGRUPADOS_Result1
{

    public Nullable<long> POSICION { get; set; }

    public string APELLIDO { get; set; }

    public string CARGO { get; set; }

    public Nullable<int> SALARIO { get; set; }

}

}
