//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptosMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntidadHospital : DbContext
    {
        public EntidadHospital()
            : base("name=EntidadHospital")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPT> DEPT { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GETMAXDEPTNO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GETMAXDEPTNO");
        }
    
        public virtual int INSERTARDEPARTAMENTO(Nullable<int> nUMERO, string nOMBRE, string lOC)
        {
            var nUMEROParameter = nUMERO.HasValue ?
                new ObjectParameter("NUMERO", nUMERO) :
                new ObjectParameter("NUMERO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var lOCParameter = lOC != null ?
                new ObjectParameter("LOC", lOC) :
                new ObjectParameter("LOC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARDEPARTAMENTO", nUMEROParameter, nOMBREParameter, lOCParameter);
        }
    
        public virtual int DATOSDEPARTAMENTOS(Nullable<int> dEPTNO, ObjectParameter pERSONAS, ObjectParameter sUMA, ObjectParameter mEDIA)
        {
            var dEPTNOParameter = dEPTNO.HasValue ?
                new ObjectParameter("DEPTNO", dEPTNO) :
                new ObjectParameter("DEPTNO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DATOSDEPARTAMENTOS", dEPTNOParameter, pERSONAS, sUMA, mEDIA);
        }
    
        public virtual ObjectResult<DEPT> GETDEPT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DEPT>("GETDEPT");
        }
    
        public virtual ObjectResult<DEPT> GETDEPT(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DEPT>("GETDEPT", mergeOption);
        }
    }
}
